format_version: 9
pipelines:
 TestingJ2Template:
    group: TestingGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/lgs/pipeline-as-a-code
        username: lgs
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - TestingJobs:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          TestingGoCDEnvironmentVariables:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - echo $SERVER_NAME
                command: sh
                run_if: passed

